service:
  name: icarus

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack # compiles and bundles together typescript code
  - serverless-finch   # deploys static web pages to S3

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:ICARUS_DEV, ''}dev
  region: eu-west-2
  profile: test

  environment:
    DROPBOX_CLIENT_ID: ${env:DROPBOX_CLIENT_ID}
    DROPBOX_CLIENT_SECRET: ${env:DROPBOX_CLIENT_SECRET}

    SLACK_TEAM_URL: ${env:SLACK_TEAM_URL}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}

    GITHUB_WEBHOOK_SECRET: ${env:GITHUB_WEBHOOK_SECRET}
    GITHUB_CLIENT_ID: ${env:GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${env:GITHUB_CLIENT_SECRET}

    TABLE_PREFIX: ${self:service}-${opt:stage, self:provider.stage}-

    ACCESSTOKENS_TABLE: ${self:provider.environment.TABLE_PREFIX}access_tokens
    SLACKACCOUNTS_TABLE: ${self:provider.environment.TABLE_PREFIX}slack_accounts

    DROPBOXACCOUNTS_TABLE: ${self:provider.environment.TABLE_PREFIX}dropbox_accounts
    DROPBOXTOKENS_TABLE: ${self:provider.environment.TABLE_PREFIX}dropbox_tokens
    DROPBOXCURSORS_TABLE: ${self:provider.environment.TABLE_PREFIX}dropbox_cursors
    FILECHANGES_TABLE: ${self:provider.environment.TABLE_PREFIX}dropbox_file_changes

    GITHUBEVENTS_TABLE: ${self:provider.environment.TABLE_PREFIX}github_events
    GITHUBACCOUNTS_TABLE: ${self:provider.environment.TABLE_PREFIX}github_accounts
    GITHUBTOKENS_TABLE: ${self:provider.environment.TABLE_PREFIX}github_tokens
custom:
  # Used by serverless-finch plugin
  client:
      bucketName: ${opt:stage, self:provider.stage}-icarus-site


functions:
  # Slack
  slack-oauth-initiate:
    handler: src/main/slack/handler.oauthInitiate
    events:
      - http:
          method: get
          path: slack-oauth-initiate
          cors: true  

  slack-oauth-complete:
    handler: src/main/slack/handler.oauthComplete
    events:
      - http:
          method: post
          path: slack-oauth-complete
          cors: true

  # Dropbox
  dropbox-webhook-challenge:
    handler: src/main/dropbox/handler.webhookChallenge
    events:
      - http:
          method: get
          path: dropbox-webhook

  dropbox-webhook-notify:
    handler: src/main/dropbox/handler.webhookNotify
    events:
      - http:
          method: post
          path: dropbox-webhook

  dropbox-oauth-initiate:
    handler: src/main/dropbox/handler.oauthInitiate
    events:
      - http:
          method: post
          path: dropbox-oauth-initiate
          cors: true

  dropbox-oauth-complete:
    handler: src/main/dropbox/handler.oauthComplete
    events:
      - http:
          method: post
          path: dropbox-oauth-complete
          cors: true

  dropbox-user-report:
    handler: src/main/dropbox/handler.userReport
    events:
      - http:
          method: get
          path: dropbox-user-report


  # Github
  gihub-webhook-receive:
    handler: src/main/github/handler.webhookReceive
    events:
      - http:
          method: post
          path: github-webhook

  github-oauth-initiate:
    handler: src/main/github/handler.oauthInitiate
    events:
      - http:
          method: post
          path: github-oauth-initiate
          cors: true

  github-oauth-complete:
    handler: src/main/github/handler.oauthComplete
    events:
      - http:
          method: post
          path: github-oauth-complete
          cors: true

resources:
  Resources:
    AccessTokensTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.ACCESSTOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: access_token
            AttributeType: S
        KeySchema:
          - AttributeName: access_token
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 10

    SlackAccountsTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.SLACKACCOUNTS_TABLE}
        AttributeDefinitions:
          - AttributeName: slack_id
            AttributeType: S
        KeySchema:
          - AttributeName: slack_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    DropboxAccountsTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DROPBOXACCOUNTS_TABLE}
        AttributeDefinitions:
          - AttributeName: slack_id
            AttributeType: S
        KeySchema:
          - AttributeName: slack_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    DropboxTokensTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DROPBOXTOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: account_id
            AttributeType: S
        KeySchema:
          - AttributeName: account_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    DropboxCursorsTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DROPBOXCURSORS_TABLE}
        AttributeDefinitions:
          - AttributeName: account_id
            AttributeType: S
        KeySchema:
          - AttributeName: account_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    FileChangesTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.FILECHANGES_TABLE}
        AttributeDefinitions:
          - AttributeName: account_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: account_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 10

    GithubEventsTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.GITHUBEVENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: S
          - AttributeName: "username"
            AttributeType: S
          - AttributeName: "timestamp"
            AttributeType: S
        KeySchema:
          - AttributeName: "id"
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: "events_by_user"
            KeySchema:
            - AttributeName: "username"
              KeyType: HASH
            - AttributeName: "timestamp"
              KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 10
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 10

    GithubAccountsTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.GITHUBACCOUNTS_TABLE}
        AttributeDefinitions:
          - AttributeName: slack_id
            AttributeType: S
        KeySchema:
          - AttributeName: slack_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    GithubTokensTable:
      Type: AWS::DynamoDB::Table
      # TODO Comment out the DeletionPolicy to make `serverless remove` deleting the table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.GITHUBTOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn:
        - GithubTokensTable
        - GithubAccountsTable
        - GithubEventsTable
        - DropboxTokensTable
        - DropboxCursorsTable
        - FileChangesTable
        - AccessTokensTable
        - SlackAccountsTable
        - DropboxAccountsTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:BatchWriteItem
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.DROPBOXTOKENS_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.DROPBOXCURSORS_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.FILECHANGES_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.ACCESSTOKENS_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.SLACKACCOUNTS_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.DROPBOXACCOUNTS_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.GITHUBEVENTS_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.GITHUBACCOUNTS_TABLE}
                - arn:aws:dynamodb:*:*:table/${self:provider.environment.GITHUBTOKENS_TABLE}
        Roles:
          - Ref: IamRoleLambdaExecution
